main:
  - name: NS
    url: /ns/
    weight: 1
  - name: Researchers
    url: /researchers/
    weight: 2
  - name: Reading
    url: /reading/
    weight: 3
  - name: Prof (CN)
    url: /cnprof/
    weight: 4
  - name: Projects
    url: /projects/
    weight: 5
  - name: Data
    url: /data/
    weight: 6
  - name: Codes
    url: /codes/
    weight: 7
  - name: Conferences
    url: /conferences/
    weight: 8
  - name: Books
    url: /books/
    weight: 9
  - name: Jobs
    url: /jobs/
    weight: 10
  - name: Utilities
    url: /utilities/
    weight: 11
  - name: Lists
    url: /lists/
    weight: 12
  - name: Galleries
    url: /galleries/
    weight: 13
  - name: CLI
    url: /cli/
    weight: 14
